package listen

import (
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	configpkg "github.com/tuannvm/ccc/pkg/config"
	"github.com/tuannvm/ccc/pkg/lookup"
	loggingpkg "github.com/tuannvm/ccc/pkg/logging"
	"github.com/tuannvm/ccc/pkg/telegram"
	"github.com/tuannvm/ccc/pkg/tmux"
)

// HandleWorktreeCommand handles the /worktree command - create worktree session from existing session
func HandleWorktreeCommand(cfg *configpkg.Config, chatID, threadID int64, text string, worktreeAutoGenerate string) {
	args := strings.TrimSpace(strings.TrimPrefix(text, "/worktree"))
	parts := strings.Fields(args)

	var baseSessionName, worktreeName string
	autoGenerated := false

	// Determine base session and worktree name based on args and context
	if len(parts) == 0 && threadID > 0 {
		// No args in topic: use current session as base, let Claude generate worktree name
		baseSessionName = lookup.GetSessionByTopic(cfg, threadID)
		if baseSessionName == "" {
			telegram.SendMessage(cfg, chatID, threadID, "❌ No active session. Use /new to create a session first.")
			return
		}

		baseSession, exists := cfg.Sessions[baseSessionName]
		if !exists || baseSession == nil {
			telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("❌ Session '%s' not found.", baseSessionName))
			return
		}

		basePath := lookup.GetSessionWorkDir(cfg, baseSessionName, baseSession)
		gitCmd := exec.Command("git", "-C", basePath, "rev-parse", "--is-inside-work-tree")
		if out, err := gitCmd.Output(); err != nil || strings.TrimSpace(string(out)) != "true" {
			telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("❌ Session '%s' is not a git repository: %s\n\nCannot create worktree. Initialize git first with 'git init'.", baseSessionName, basePath))
			return
		}

		providerName := baseSession.ProviderName
		if providerName == "" {
			providerName = cfg.ActiveProvider
		}

		existingWorktrees := lookup.GetWorktreeNames(basePath)
		if existingWorktrees == nil {
			existingWorktrees = make(map[string]bool)
		}

		telegram.SendMessage(cfg, chatID, threadID, "🌳 Creating worktree...")
		loggingpkg.ListenLog("[/worktree] Starting Claude with --worktree for %s in %s (existing worktrees: %d)", baseSessionName, basePath, len(existingWorktrees))

		if err := tmux.SwitchSessionInWindow(baseSessionName, basePath, providerName, "", worktreeAutoGenerate, false, false); err != nil {
			telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("❌ Failed to start Claude: %v", err))
			return
		}

		worktreeName = lookup.WaitForNewWorktree(basePath, existingWorktrees, 30*time.Second)
		if worktreeName == "" {
			telegram.SendMessage(cfg, chatID, threadID, "❌ Failed to detect generated worktree name (timeout after 30s)\n\n💡 Tip: A worktree may have been created. Check with: git worktree list")
			return
		}

		loggingpkg.ListenLog("[/worktree] Detected worktree name: %s", worktreeName)
		worktreeSessionName := baseSessionName + "_" + worktreeName
		autoGenerated = true

		topicID, err := telegram.CreateForumTopic(cfg, worktreeSessionName, providerName, baseSessionName)
		if err != nil {
			telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("❌ Failed to create topic: %v", err))
			return
		}

		worktreePath := filepath.Join(basePath, ".claude", "worktrees", worktreeName)
		cfg.Sessions[worktreeSessionName] = &configpkg.SessionInfo{
			TopicID:      topicID,
			Path:         worktreePath,
			ProviderName: providerName,
			IsWorktree:   true,
			WorktreeName: worktreeName,
			BaseSession:  baseSessionName,
		}
		configpkg.Save(cfg)

		if err := EnsureHooks(cfg, worktreeSessionName, cfg.Sessions[worktreeSessionName]); err != nil {
			loggingpkg.ListenLog("[/worktree] Failed to install hooks for %s: %v", worktreeSessionName, err)
		}

		if err := tmux.SwitchSessionInWindow(worktreeSessionName, basePath, providerName, "", worktreeName, false, false); err != nil {
			telegram.SendMessage(cfg, cfg.GroupID, topicID, fmt.Sprintf("❌ Failed to start session: %v", err))
			return
		}

		providerMsg := ""
		if providerName != "" {
			providerMsg = fmt.Sprintf("\n🤖 Provider: %s", providerName)
		}
		worktreeMsg := fmt.Sprintf("🌳 Worktree session '%s' started!\nBase: %s\nWorktree: %s%s\n\n✨ Worktree name was auto-generated by Claude", worktreeSessionName, baseSessionName, worktreeName, providerMsg)
		worktreeMsg += "\n\nSend messages here to interact with Claude."
		telegram.SendMessage(cfg, cfg.GroupID, topicID, worktreeMsg)
		return
	}

	if len(parts) == 1 && threadID > 0 {
		worktreeName = parts[0]
		baseSessionName = lookup.GetSessionByTopic(cfg, threadID)
		if baseSessionName == "" {
			telegram.SendMessage(cfg, chatID, threadID, "❌ No active session. Use /new to create a session first, or use: /worktree <session_name> <worktree_name>")
			return
		}
	} else if len(parts) == 1 {
		telegram.SendMessage(cfg, chatID, threadID, "Usage: /worktree <session_name> <worktree_name>\n\nCreates a new worktree session from an existing session's repository.\n\nTip: In a session topic, you can use just /worktree <name>.")
		return
	} else if len(parts) == 2 {
		baseSessionName = parts[0]
		worktreeName = parts[1]
	} else {
		telegram.SendMessage(cfg, chatID, threadID, "Usage: /worktree <session_name> <worktree_name>\n\nTip: in a session topic, use /worktree or /worktree <name>.")
		return
	}

	baseSession, exists := cfg.Sessions[baseSessionName]
	if !exists || baseSession == nil {
		telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("❌ Base session '%s' not found. Use /new to create it first.", baseSessionName))
		return
	}

	basePath := lookup.GetSessionWorkDir(cfg, baseSessionName, baseSession)
	gitCmd := exec.Command("git", "-C", basePath, "rev-parse", "--is-inside-work-tree")
	if out, err := gitCmd.Output(); err != nil || strings.TrimSpace(string(out)) != "true" {
		telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("❌ Base session path is not a git repository: %s", basePath))
		return
	}

	worktreeSessionName := baseSessionName + "_" + worktreeName

	if _, exists := cfg.Sessions[worktreeSessionName]; exists {
		telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("⚠️ Worktree session '%s' already exists. Use /new in that topic to restart.", worktreeSessionName))
		return
	}

	providerName := baseSession.ProviderName
	if providerName == "" {
		providerName = cfg.ActiveProvider
	}

	topicID, err := telegram.CreateForumTopic(cfg, worktreeSessionName, providerName, baseSessionName)
	if err != nil {
		telegram.SendMessage(cfg, chatID, threadID, fmt.Sprintf("❌ Failed to create topic: %v", err))
		return
	}

	worktreePath := filepath.Join(basePath, ".claude", "worktrees", worktreeName)
	cfg.Sessions[worktreeSessionName] = &configpkg.SessionInfo{
		TopicID:      topicID,
		Path:         worktreePath,
		ProviderName: providerName,
		IsWorktree:   true,
		WorktreeName: worktreeName,
		BaseSession:  baseSessionName,
	}
	configpkg.Save(cfg)

	if err := EnsureHooks(cfg, worktreeSessionName, cfg.Sessions[worktreeSessionName]); err != nil {
		loggingpkg.ListenLog("[/worktree] Failed to install hooks for %s: %v", worktreeSessionName, err)
	}

	if err := tmux.SwitchSessionInWindow(worktreeSessionName, basePath, providerName, "", worktreeName, false, false); err != nil {
		telegram.SendMessage(cfg, cfg.GroupID, topicID, fmt.Sprintf("❌ Failed to start session: %v", err))
		return
	}

	providerMsg := ""
	if providerName != "" {
		providerMsg = fmt.Sprintf("\n🤖 Provider: %s", providerName)
	}
	worktreeMsg := fmt.Sprintf("🌳 Worktree session '%s' started!\nBase: %s\nWorktree: %s%s", worktreeSessionName, baseSessionName, worktreeName, providerMsg)
	if autoGenerated {
		worktreeMsg += "\n\n✨ Worktree name was auto-generated"
	}
	worktreeMsg += "\n\nSend messages here to interact with Claude."
	telegram.SendMessage(cfg, cfg.GroupID, topicID, worktreeMsg)
}
